### ISSUE TITLE
Kessac 512 - How-to Question

### ISSUE THREAD

**Issue by bennyDeveloper** [crdrost/sha3-js#1]
I didn't find any contact email, so I am opening an issue :)

Anyway, I want to implement hashing with kessac 512
My code looks like this:

```
    var keccakFun = keccak;
    password = keccakFun(password);
    alert("password!!!"+password+"!!!");
```

It works, But the this is not kessac 512.
So what do I need to do in order to hash by kessac 512
me email is: benny@bdapps.net

10x in advance :)

Benny

**Comment by mmsaffari** [comment]
How do you know it is not KECCAK-512?
Could you please provide the password and the result you get?

**Comment by bennyDeveloper** [comment]
if the password is 123456
kessac 512 is:
808d63ba47fcef6a7c52ec47cb63eb1b747a9d527a77385fc05c8a5ce8007586265d003b4130f6b0c8f3bb2ad89965a5da07289ba5d1e35321e160bea4f766f8
kessac 256 is:
c888c9ce9e098d5864d3ded6ebcc140a12142263bace3a23a36f9905f12bd64a

And your code result
is: e2483089481d5d8c53c00e806914cbc0ea4cfaea53326709ddbaed86315a0268

2013/6/19 mmsaffari notifications@github.com

> How do you know it is not KECCAK-512?
> Could you please provide the password and the result you get?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/drostie/sha3-js/issues/1#issuecomment-19688541
> .

## 

בני דוידוביץ
BDApps
מייסד ומתכנת
052-7790800
benny@bdapps.net

**Comment by mmsaffari** [comment]
OK.
I just read the 2nd paragraph of keccak.js and it says this file implements SHA3-256 bits...

**Comment by mmsaffari** [comment]
- This file implements Keccak[1088, 512, 32], their proposed candidate for 
- SHA3-256. This implementation operates on Javascript strings, interpreted as 
- UTF-16LE encoded (i.e. "\u1234\u5678" --> [0x34, 0x12, 0x78, 0x56], and thus 
- is restricted to hash byte strings which are a multiple of 2 bytes in 
- length.

**Comment by mmsaffari** [comment]
and this is not my code BTW :)

**Comment by bennyDeveloper** [comment]
I had read the readme,
But still there is no explanation how to make it work with 512 and not 32 or 1088

**Comment by mmsaffari** [comment]
According to the comments on the keccak.js file, the only implementation here is 256-bits.
You may consider using this instead:
https://code.google.com/p/crypto-js/#SHA-3

**Comment by bennyDeveloper** [comment]
10x a lot, you helped me much!

**Comment by mmsaffari** [comment]
You're welcome :+1:
